name: Google Calendar Cinema Event Manager Pull Request

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    container:
      image: node:19
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npm run lint